 # This file defines two services, the db service and web service
 version: '2'
 services:
   postgres:
     restart: always # restart db service if it crashes
     image: postgres
     env_file: env
     expose:
       - "5432"

   wiki:
      build : ./wiki/
      restart: always
      image: wiki
      volumes:
        - /srv/html
      expose:
        - "3000"

   web:
     build : ./webpage/
     hostname: production
     restart: always # restart web server if it crashes
     image: web
     command: bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && gunicorn lascilab.wsgi -b 0.0.0.0:8000"
     volumes: 
       - ./webpage:/webpage
     expose:
       - "8000"
     links:
       - postgres:postgres
     env_file: env
 
   nginx:
     build : ./nginx/
     restart: always
     image: nginx
     ports: 
       - "80:80"
     volumes:
       - /www/static
     volumes_from:
       - web
       - wiki
     links:
       - web:web
