# Generated by Django 2.0.6 on 2018-07-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Name')),
                ('banner', models.ImageField(blank=True, help_text='preferably in PNG format', null=True, upload_to='', verbose_name='Image')),
                ('important_notes', models.TextField(blank=True, null=True, verbose_name='Important Notes')),
                ('application_opening', models.DateField(verbose_name='Application Opening')),
                ('application_deadline', models.DateField(verbose_name='Application Deadline')),
                ('admission_notification', models.DateField(blank=True, null=True, verbose_name='Admission Notification')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('registration_form_url', models.URLField(blank=True, null=True, verbose_name='Registration Form URL')),
                ('feedback_form_url', models.URLField(blank=True, null=True, verbose_name='Feedback Form URL')),
                ('mission', models.TextField(blank=True, null=True, verbose_name='Event Mision')),
                ('program_url', models.URLField(blank=True, null=True, verbose_name='Program URL')),
                ('venue', models.TextField(blank=True, null=True, verbose_name='Venue')),
                ('costs', models.TextField(blank=True, null=True, verbose_name='Cost')),
                ('speakers', models.ManyToManyField(blank=True, to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Topic')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='seminar',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='event.Sponsor'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='topics',
            field=models.ManyToManyField(to='event.Topic'),
        ),
        migrations.AddField(
            model_name='memory',
            name='seminar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Seminar'),
        ),
    ]
