# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Picture')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Github Account URL')),
                ('google_url', models.URLField(blank=True, null=True, verbose_name='Google Account URL')),
                ('youtube_channel_url', models.URLField(blank=True, null=True, verbose_name='Youtube Channer URL')),
                ('webpage_url', models.URLField(blank=True, null=True, verbose_name='Web Page URL')),
                ('description', models.TextField(verbose_name='About Me')),
                ('interest', models.TextField(verbose_name='Areas of Interest')),
                ('affiliation', models.CharField(max_length=500, verbose_name='Affiliation')),
                ('laboratory', models.CharField(max_length=500, verbose_name='Laboratory')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='person_set', to='auth.Group', verbose_name='groups')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
