# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20170212_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
