# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20170212_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='About Me'),
        ),
    ]
