# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Picture')),
                ('important_notes', models.TextField(blank=True, null=True, verbose_name='Important Notes')),
                ('application_opening', models.DateField(blank=True, null=True, verbose_name='Application Opening')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Application Deadline')),
                ('admission_notification', models.DateField(blank=True, null=True, verbose_name='Admission Notification')),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name='Registration Deadline')),
                ('mision', models.TextField(blank=True, null=True, verbose_name='Event Mision')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Organization')),
                ('venue', models.TextField(blank=True, null=True, verbose_name='Event Venue')),
                ('costs', models.TextField(blank=True, null=True, verbose_name='Event Cost')),
                ('program_picture', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Program Picture')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Event Topic')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(to='event.EventImage'),
        ),
        migrations.AddField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(to='event.Topic'),
        ),
    ]
