# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170125_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='costs',
            field=models.TextField(blank=True, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.TextField(blank=True, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.TextField(blank=True, null=True, verbose_name='Venue'),
        ),
    ]
