# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20170130_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organization',
        ),
    ]
