# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Name')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Picture')),
                ('important_notes', models.TextField(blank=True, null=True, verbose_name='Important Notes')),
                ('application_opening', models.DateField(blank=True, null=True, verbose_name='Application Opening')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Application Deadline')),
                ('admission_notification', models.DateField(blank=True, null=True, verbose_name='Admission Notification')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('registration_form_url', models.URLField(blank=True, null=True, verbose_name='Registration Form URL')),
                ('feedback_form_url', models.URLField(blank=True, null=True, verbose_name='Feedback Form URL')),
                ('mision', models.TextField(blank=True, null=True, verbose_name='Event Mision')),
                ('venue', models.TextField(blank=True, null=True, verbose_name='Venue')),
                ('costs', models.TextField(blank=True, null=True, verbose_name='Cost')),
                ('program', models.URLField(blank=True, null=True, verbose_name='Program URL')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Picture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Topic')),
            ],
        ),
    ]
