# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeaker',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='topics',
            field=models.ManyToManyField(to='event.Topic'),
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(to='event.EventImage'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(to='event.Sponsor'),
        ),
        migrations.AddField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(to='event.Topic'),
        ),
    ]
