# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventspeaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Name'),
        ),
    ]
